const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openFileDialog: () => ipcRenderer.invoke('dialog:openFile'),
  openPDFDialog: () => ipcRenderer.invoke('dialog:openPDF'),
  readFile: (filePath) => ipcRenderer.invoke('file:read', filePath),
  storeLoad: () => ipcRenderer.invoke('store:load'),
  storeSave: (data) => ipcRenderer.invoke('store:save', data),
  storeLoadDictionary: () => ipcRenderer.invoke('store:loadDictionary'),
  storeLoadC1Dictionary: () => ipcRenderer.invoke('store:loadC1Dictionary'),
  storeLoadVerbDictionary: () => ipcRenderer.invoke('store:loadVerbDictionary'),
  storeLoadTags: () => ipcRenderer.invoke('store:loadTags'),
  loadFavoritesFile: () => ipcRenderer.invoke('store:loadFavoritesFile'),
  collectionLoad: () => ipcRenderer.invoke('collection:load'),
  collectionAdd: (word) => ipcRenderer.invoke('collection:add', word),
  collectionRemove: (word) => ipcRenderer.invoke('collection:remove', word),
  readDir: (dirPath) => ipcRenderer.invoke('fs:readdir', dirPath),
  getHomeDir: () => ipcRenderer.invoke('fs:getHomeDir'),
  openAnyDialog: () => ipcRenderer.invoke('dialog:openAny'),
  translateWord: (word, from, langs, count) => ipcRenderer.invoke('translate:word', { word, from, langs, count }),
  dictionaryAdd: (entry) => ipcRenderer.invoke('dictionary:add', entry),
  dictionaryRemove: (id) => ipcRenderer.invoke('dictionary:remove', id),
  dictionaryLoad: () => ipcRenderer.invoke('dictionary:load'),
  youtubeCaptions: (videoId) => ipcRenderer.invoke('youtube:captions', videoId),
  vocabLibLoadMeta: () => ipcRenderer.invoke('vocablib:loadMeta'),
  vocabLibSaveMeta: (data) => ipcRenderer.invoke('vocablib:saveMeta', data),
  vocabLibUpdatePosition: (youtubeUrl, position) => ipcRenderer.invoke('vocablib:updatePosition', youtubeUrl, position),
  vocabLibDeleteVideo: (youtubeUrl) => ipcRenderer.invoke('vocablib:deleteVideo', youtubeUrl),
  vocabLibDeleteWord: (wordId) => ipcRenderer.invoke('vocablib:deleteWord', wordId),
  ttsSpeak: (text, lang, voice) => ipcRenderer.invoke('tts:speak', { text, lang, voice }),
});
