const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openFileDialog: () => ipcRenderer.invoke('dialog:openFile'),
  openPDFDialog: () => ipcRenderer.invoke('dialog:openPDF'),
  readFile: (filePath) => ipcRenderer.invoke('file:read', filePath),
  storeLoad: () => ipcRenderer.invoke('store:load'),
  storeSave: (data) => ipcRenderer.invoke('store:save', data),
  storeLoadDictionary: () => ipcRenderer.invoke('store:loadDictionary'),
  storeLoadC1Dictionary: () => ipcRenderer.invoke('store:loadC1Dictionary'),
  storeLoadVerbDictionary: () => ipcRenderer.invoke('store:loadVerbDictionary'),
  storeLoadTags: () => ipcRenderer.invoke('store:loadTags'),
  loadFavoritesFile: () => ipcRenderer.invoke('store:loadFavoritesFile'),
  collectionLoad: () => ipcRenderer.invoke('collection:load'),
  collectionAdd: (word) => ipcRenderer.invoke('collection:add', word),
  collectionRemove: (word) => ipcRenderer.invoke('collection:remove', word),
  readDir: (dirPath) => ipcRenderer.invoke('fs:readdir', dirPath),
  getHomeDir: () => ipcRenderer.invoke('fs:getHomeDir'),
  openAnyDialog: () => ipcRenderer.invoke('dialog:openAny'),
  translateWord: (word) => ipcRenderer.invoke('translate:word', word),
  dictionaryAdd: (entry) => ipcRenderer.invoke('dictionary:add', entry),
  dictionaryRemove: (id) => ipcRenderer.invoke('dictionary:remove', id),
  dictionaryLoad: () => ipcRenderer.invoke('dictionary:load'),
  youtubeCaptions: (videoId) => ipcRenderer.invoke('youtube:captions', videoId),
});
